apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-artifactory-ha-primary
  labels:
    metrics: jfrog
    app: kube-prometheus-stack-prometheus
    release: jfrog-prometheus
spec:
  selector:
    matchLabels:
      app: artifactory-ha-primary
  endpoints:
  - port: metrics
    interval: 15s