apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-xray
  labels:
    metrics: jfrog
    app: kube-prometheus-stack-prometheus
    release: jfrog-prometheus
spec:
  selector:
    matchLabels:
      app: xray
  endpoints:
  - port: metrics
    interval: 15s