global:
  jfrog:
    observability:
      branch: prometheus_revamp
  prometheus: 
    loki_url: http:\/\/10.96.105.82
unifiedUpgradeAllowed: true
databaseUpgradeReady: true
xray:
  jfrogUrl: http://artifactory-artifactory.rt:8082
replicaCount: 1
postgresql:
  postgresqlPassword: xray
rabbitmq-ha:
  enabled: false
rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest
common:
  customSidecarContainers: |
    - name: "xray-fluentd-sidecar"
      image: "partnership-public-images.jfrog.io/fluentd/fluentd:1.18.0"
      imagePullPolicy: "IfNotPresent"
      command:
        - 'sh'
        - '-c'
        - >
          gem install fluent-plugin-prometheus --no-doc;
          curl https://raw.githubusercontent.com/jfrog/log-analytics-prometheus/{{ .Values.global.jfrog.observability.branch }}/fluent.conf.xray -o fluent.conf.xray;
          cp fluent.conf.xray fluent.tmp.conf;
          sed -i -e 's/LOKI_URL/{{ .Values.global.prometheus.loki_url }}/g' fluent.tmp.conf;
          mv fluent.tmp.conf fluentd.conf;
          fluentd -v -c fluentd.conf;
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.xray.persistence.mountPath }}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf
## Allows to add additional kubernetes resources
## Use --- as a separator between multiple resources
## For an example, refer - https://github.com/jfrog/log-analytics-prometheus
additionalResources: |
  apiVersion: v1
  kind: Service
  metadata:
    name: {{ template "xray.fullname" . }}-metrics
    annotations:
      prometheus.io/path: "/metrics"
      prometheus.io/scheme: "http"
      prometheus.io/port: "24231"
      prometheus.io/scrape: "true"
    labels:
      app: {{ template "xray.name" . }}
      chart: {{ template "xray.chart" . }}
      component: metrics
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      {{- with .Values.xray.labels }}
  {{ toYaml . | indent 4 }}
      {{- end }}
  spec:
    type: ClusterIP
    ports:
    - name: metrics
      port: 24231
      protocol: TCP
    selector:
      app: {{ template "xray.name" . }}
      component: "{{ .Values.xray.name }}"
      release: {{ .Release.Name }}
  ---
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: servicemonitor-{{ template "xray.name" . }}
    labels:
      metrics: jfrog
      app: {{ template "xray.name" . }}
      chart: {{ template "xray.chart" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  spec:
    selector:
      matchLabels:
        app: {{ template "xray.name" . }}
        component: metrics
    endpoints:
      - port: metrics
        interval: 15s
